# Generated by Django 5.1.1 on 2024-10-01 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('click_games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='opcaoComputador',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='opcaoUsuario',
        ),
        migrations.AddField(
            model_name='jogo',
            name='opcao_computador',
            field=models.CharField(choices=[('pedra', 'Pedra'), ('papel', 'Papel'), ('tesoura', 'Tesoura')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jogo',
            name='opcao_usuario',
            field=models.CharField(choices=[('pedra', 'Pedra'), ('papel', 'Papel'), ('tesoura', 'Tesoura')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicologin',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogos', to=settings.AUTH_USER_MODEL),
        ),
    ]
